name: Flutter Web Deploy

on:
  push:
    branches:
      - master  # Trigger deployment on push to master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}  # Use the token here for authentication

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'  # Correct Flutter version

      - name: Install dependencies
        run: |
          cd ./  # Adjust if your Flutter project is in a subdirectory
          flutter pub get

      - name: Build Flutter Web App
        run: |
          cd ./  # Ensure you're in the correct directory
          flutter build web --release

      - name: Set up secrets for essential.json
        run: |
          mkdir -p config
          echo '{
            "apiUrl": "${{ secrets.APIURL }}",
            "anonKey": "${{ secrets.ANONKEY }}"
          }' > config/essential.json

      - name: Stash any local changes before switching branches
        run: |
          git stash -u  # Stashes both tracked and untracked files

      - name: Copy build output to stable branch root
        run: |
          git fetch origin stable
          git checkout stable
          cp -r build/web/* .  # Copy the build output to the stable branch

      - name: Commit and push changes to stable
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy Flutter Web app to GitHub Pages" || echo "No changes to commit"
          git push origin stable --force

      - name: Apply stashed changes after deployment (if any)
        run: |
          git checkout master
          git stash pop || echo "No stashed changes"
