name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web app
        run: flutter build web --release

      - name: List build directory contents (debugging step)
        run: ls -l build/web

      - name: Setup Git for deploying
        run: |
          git config --global user.name "Minarul Ali"
          git config --global user.email "minarul.ali@outlook.com"

      - name: Checkout stable branch
        run: |
          git fetch origin stable
          git checkout stable

      - name: Copy build/web to stable branch
        run: |
          if [ -d "build/web" ]; then
            rm -rf *  # Clear previous content in the stable branch
            cp -R build/web/* .  # Copy new build content
          else
            echo "Error: build/web not found"
            exit 1
          fi

      - name: Commit and push to stable
        run: |
          git add .
          git commit -m "Update GitHub Pages"
          git push origin stable
