name: Flutter Web Deploy

on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger the deployment (e.g., 'master')

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'  # Make sure to use the correct Flutter version

      - name: Install dependencies
        run: |
          cd ./  # If your Flutter project is in a subdirectory, change this path to the correct one
          flutter pub get

      - name: Build Flutter Web App
        run: |
          cd ./  # Make sure you are in the correct directory
          flutter build web --release

      - name: Set up secrets for essential.json
        run: |
          mkdir -p config
          echo '{
            "apiUrl": "${{ secrets.APIURL }}",
            "anonKey": "${{ secrets.ANONKEY }}"
          }' > config/essential.json

      - name: Copy build output to stable branch root
        run: |
          git fetch origin stable
          git checkout stable
          cp -r build/web/* .

      - name: Commit and push changes to stable
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy Flutter Web app to GitHub Pages"
          git push origin stable --force
